name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "2.6.6"
      - name: Run deno lint
        run: deno lint

  fmt:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "2.6.6"
      - name: Run deno fmt --check
        run: deno fmt --check

  jsdoc:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "2.6.6"
      - name: Run JSDoc lint
        run: deno task jsdoc:lint

  test_and_coverage:
    runs-on: ubuntu-24.04-arm
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "2.6.6"
      - name: Run tests with coverage enabled
        run: deno task test:ci
      - name: Check coverage
        run: deno run -A jsr:@ashishkujoy/deno-coverage-checker
      - name: Generate LCOV report
        run: deno coverage coverage --lcov > coverage.lcov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.lcov
      - name: Publish test results
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Test Results
          path: test-results.xml
          reporter: java-junit

  validate-pr-title:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04-arm
    permissions:
      pull-requests: read
    steps:
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
